name: E2E Testing (Develop)

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: trigger_internal
  schedule:
    - cron: '0 22 * * *'

env:
  PROJECT_NAME: 'playwright-test'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        if: success() || failure()
        id: setup
        run: |
          TODAY_DATE=`date +"%d.%m.%y"`
          echo "::set-output name=DATE::$TODAY_DATE"
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"
          echo "::set-output name=PROJECT::$PROJECT_NAME/develop/$TODAY_DATE"v
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Generate report
        if: success() || failure()
        run: |
          mv playwright-report/index.html playwright-report/index.html
      - name: Move all report to today date
        if: success() || failure()
        run: 
          mv playwright-report ${{steps.setup.outputs.DATE}}
      - name: Send notification to slack
        uses: 8398a7/action-slack@v2
        if: success() || failure()
        with:
          status: ${{ job.status }}
          author_name:
            Tester report
          text:
            'Can check report at:
            http://automated-tester.s3-website-ap-southeast-1.amazonaws.com/${{steps.setup.outputs.PROJECT}}/index.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}