name: E2E Testing (Develop)

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: trigger_internal
  schedule:
    - cron: '0 22 * * *'

env:
  PROJECT_NAME: 'playwright-test'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        if: success() || failure()
        id: setup
        run: |
          TODAY_DATE=`date +"%d.%m.%y"`
          echo "::set-output name=DATE::$TODAY_DATE"
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"
          echo "::set-output name=PROJECT::$PROJECT_NAME/develop/$TODAY_DATE"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Deploy reports
        uses: bounceapp/render-action@0.2.0
        with:
          folder: 'playwright-report/${{steps.setup.outputs.DATE}}'
          bucket: 'automated-tester/${{steps.setup.outputs.PROJECT}}'
        env:
          email: ${{ secrets.RENDER_EMAIL }}
          password: ${{ secrets.RENDER_PASSWORD }}
          token: ${{ secrets.TOKEN }}
          service-id: ${{ secrets.RENDER_API_KEY }}
      - name: Send notification to slack
        uses: 8398a7/action-slack@v2
        if: success() || failure()
        with:
          status: ${{ job.status }}
          author_name:
            Tester report
          text:
            'Can check report at: https://playwright-test.onrender.com/${{steps.setup.outputs.PROJECT}}/index.html'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}